---
# tasks file for ic_it.install_fail2ban
- name: installs fail2ban # and sendmail
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - fail2ban
  # - sendmail

- name: override the base fail2ban configuration with a local file
  copy:
    src: jail.local.redhat
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  register: local_result

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
    enabled: yes
  when: local_result.changed
